apiVersion: v1
kind: Pod
metadata:
  name: dbpod
spec:
  containers:
    - name: deploy-test
      image: test/module:latest
      imagePullPolicy: Never
      resources:
        limits:
          memory: "128"
          cpu: "500"

    - name: mysql
      image: mysql
      imagePullPolicy: Always
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123"
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "123"
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: "123"
      resources:
        limits:
          memory: "128"
          cpu: "500"

