apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: dev
  labels:
    app: db-deployment
spec:
  type: NodePort
  selector:
    app: db-deployment
  ports:
  - port: 30000
    name: mysql-port
    targetPort: 3306
    nodePort: 31737
    protocol: TCP
  - port: 30001
    name: adminer-port
    targetPort: 8080
    protocol: TCP