apiVersion: v1
kind: Service
metadata:
  name: python-service
  namespace: dev
  labels:
    app: python-deployment
spec:
  type: NodePort
  selector:
    app: python-deployment
  ports:
  - port: 30002
    name: python-port
    targetPort: 5000
    protocol: TCP
  - port: 30003
    name: add-port
    targetPort: 5000
    protocol: TCP