# Deployment from python image built w/ nerdctl
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-deployment
  template:
    metadata:
      labels:
        app: python-deployment
    spec:
      containers:
        - name: python-script
          image: python-script:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
